### ISSUE TITLE
about canonical space 

### ISSUE THREAD

**Issue by emjay73** [vye16/shape-of-motion#25]
Hello, Thank you for sharing this great work!
I have some questions about the canonical space visualization.

Here is the visualization of the iphone/backpack dataset in the middle of the training process:
![image](https://github.com/user-attachments/assets/2043a7d2-fcce-4cec-a60d-c240ef866ba7)

After I mark the 'canonical' checkbox, I can see the front side of the backpack.
![image](https://github.com/user-attachments/assets/62123117-9315-434f-9831-9454dcdbedbb)

However, when I turn the 3D scene to observe the rear side of the backpack in the canonical space,
I encounter an under-reconstructed backpack.
![image](https://github.com/user-attachments/assets/925e91e9-958f-4042-bed2-88dc1f6758be)

From the first image, it seems that the shape-of-motion model is capable of reconstructing the backpack's rear side.
How is it that the rear side of the backpack is not observable in the canonical space but appears to be reconstructable from the different time steps?

Thank you for your time and assistance.

**Comment by qianqianwang68** [comment]
Great question! One possible explanation is that, Gaussians for the rear side do exist in the canonical frame, but they are not very well registered in canonical space, i.e., they do not form a coherent backpack with the other sides of the backpack. In this case, the canonical space can still reconstruct the video, it's just that the front and back side of the backpack will have to have two different sets of SE3 transformations. Of course this is not ideal because the whole backpack is moving rigidly and ideally one would want to represent the backpack's motion with a single SE3 rigid body motion. However, we found this is not easy to achieve -- it requires the model to understand rigid groups well, which we leave as future work.

Close the issue for now; feel free to reopen it if you have further questions
