### ISSUE TITLE
4D interactive viewer and benchmark results

### ISSUE THREAD

**Issue by cv-lab-x** [vye16/shape-of-motion#5]
hi, thanks for your great work, some questions about the benchmark results. could you post your novel view **results on Davis and kid-running datasets**, as you show the novel view demo on the projects, but no results reported on your paper?
and could you release the **4D interactive viewer** you used? 
Looking forward to your reply, thanks. @vye16

**Comment by vye16** [comment]
Hi! We only have qualitative results for DAVIS and the kid-running video sequences on the project website because those videos only have monocular capture (at each time step we only have a single viewpoint). We can report the novel view metrics for the iphone dataset because in those captures have _simultaneous_ multiple views at every timepoint, one which we use for training and one which we use for evaluation.

To use the interactive viewer, you can either just pass in the argument `--port [PORT]` to the `run_training.py` script during training, or to view a trained checkpoint, run `python run_rendering.py --work-dir [OUTPUT_DIR] --port [PORT]`. I will update the readme with these details.
